### ISSUE TITLE
[RFE] update anytime soon for RHEL 8.4/Ansible 2.9 Version of the Class?

### ISSUE THREAD

**Issue by Da-Geek** [tmichett/RH294#1]
$subject

**Comment by tmichett** [comment]
So I was waiting until major updates with the AAP2 stuff that comes with the RHEL9 version of the course. There was only the Ansible Collections portion @Da-Geek that was new in the RHEL 8.4 and the demo and content were/are still relevant.

I did a webinar for Red Hat Training: https://github.com/tmichett/AAP_Webinar that has a PDF guide with some collections information and demos.

I also have https://github.com/tmichett/AnsiblePlaybooks that I use for demos

What specifically are you wanting to see?

**Comment by Da-Geek** [comment]
the structure of the class in the current version is different that this repo, is all.
So its kinda difficult to find the thing where they should be.
for instance we only have a total of 10 Chapters in the current class, not 11 as in this repo

**Comment by tmichett** [comment]
Oh. I can look at fixing that. It should be an easy enough fix. I still use my guide from the older book and stuff when I deliver so I guess I never thought about it.

**Comment by tmichett** [comment]
@Da-Geek - I've created a RH80 release for the older RH294 and I've updated the structure of the course for the RHEL 8.4 version of the course and created a release for that too! Let me know if this works and I'll close the issue.
